### ISSUE TITLE
how do I fuzz another rust project? 

### ISSUE THREAD

**Issue by peilinfeng** [duytai/fuzz-demo#1]
I have a question. How do I fuzz another rust project? And how does the instrument.sh works to build a png interface to connect with afl. Thank you.

**Comment by duytai** [comment]
1. You can add your project as a binary target of the current project and run instrument again. For example, I added png to file cargo.toml as follows.
```
[[bin]]
name = "png"
path = "bin/png.rs"
```
2. You may notice that there is a static library ```libafl-llvm-rt.a``` in programs/ folder, which contains interface to communicate with AFL. Source code: https://github.com/google/AFL/blob/master/llvm_mode/afl-llvm-rt.o.c

3. In that static library, AFL implements forkserver (https://github.com/google/AFL/blob/master/llvm_mode/afl-llvm-rt.o.c#L103) and callback functions for sancov pass (https://github.com/google/AFL/blob/master/llvm_mode/afl-llvm-rt.o.c#L275). 
    - forkserver: https://github.com/mirrorer/afl/blob/master/docs/technical_details.txt#L446
    - sancov pass: https://clang.llvm.org/docs/SanitizerCoverage.html

**Comment by peilinfeng** [comment]
Thanks for your help @duytai
